### ISSUE TITLE
how to make this project

### ISSUE THREAD

**Issue by ccfeiker** [cihangirtezcan/CUDA_AES#1]
hello Mr.cihangirtezcan
I want to run this program, But I don’t know how to compile this project, I would like to ask you

**Comment by cihangirtezcan** [comment]
Hello. This is a CUDA project. So you need to install CUDA SDK for your compiler. If you are using Windows, you can compile this project using Visual Studio. Installing CUDA SDK after you installed Visual Studio is generally better. You need to compile AES_final.cu to produce an executable. Hope this helps.

**Comment by 905799575** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ccfeiker** [comment]
> Hello. This is a CUDA project. So you need to install CUDA SDK for your compiler. If you are using Windows, you can compile this project using Visual Studio. Installing CUDA SDK after you installed Visual Studio is generally better. You need to compile AES_final.cu to produce an executable. Hope this helps.

Thank your reply
I already intall CUDA SDK, i use th command : nvcc AES.final.cu -o AES.final.  but it's failed could you share with me a CMakeLists.txt or Makefile? Thanks

**Comment by cihangirtezcan** [comment]
I compiled it on Windows so I do not have Makefile. If you can post the compile error, we can pinpoint where the problem lies.

**Comment by ccfeiker** [comment]
> I compiled it on Windows so I do not have Makefile. If you can post the compile error, we can pinpoint where the problem lies.
command: nvcc AES_final.cu -o AES_final
errors:
file-encryption.cuh(451): error: no instance of constructor "std::basic_fstream<_CharT, _Traits>::basic_fstream [with _CharT=char, _Traits=std::char_traits<char>]" matches the argument list
            argument types are: (const std::string, std::_Ios_Openmode)

file-encryption.cuh(599): error: no instance of constructor "std::basic_fstream<_CharT, _Traits>::basic_fstream [with _CharT=char, _Traits=std::char_traits<char>]" matches the argument list
            argument types are: (const std::string, std::_Ios_Openmode)

2 errors detected in the compilation of "/tmp/tmpxft_00002583_00000000-8_AES_final.cpp1.ii".

**Comment by cihangirtezcan** [comment]
Looks like it is a C++ problem about file reading and writing. Try including the fstream library to the file-encryption.cuh file. It should be something like: 
#include <fstream.h>

**Comment by ccfeiker** [comment]
this problem is c++ problem. std:string is c++ library but i use the nvcc complier, so can't solve this problem. but it doesn't matter. I Annotation mainFileEncryption this function.run this program, I scanf chioce is 8,this program print:
(1)  AES-128 Exhaustive Search (no bank conflict, byteperm)
(11) AES-128 Exhaustive Search (no bank conflict, arithmetic shift)
(2) AES-128 Exhaustive Search (conflicting S-box, arithmetic shift)
(22) AES-128 Exhaustive Search (conflicting S-box, byteperm)
(3) AES-128 CTR 
(4) AES-192 Exhaustive Search
(5) AES-192 CTR
(6) AES-256 Exhaustive Search
(7) AES-256 CTR
(8) ALL
Choice: 8

########## AES-128 Exhaustive Search Implementation ##########

-------------------------------
! Found key : 2b7e1516 28aed2a6 abf71588 09cf4f3c
-------------------------------
Time elapsed: 3.690000 sec
-------------------------------

########## AES-128 Counter Mode Implementation ##########

-------------------------------
threadIndex : 1048575
Plaintext   : 3243f6a8 885a308d 313198aa 00000000
Ciphertext  : 4fd0a24c be277301 81ca99bd 9960050b
-------------------------------
Time elapsed: 2.820000 sec
-------------------------------
plaintext: 2b7e1516 28aed2a6 abf71588 9cf4f3c

########## AES-192 Exhaustive Search Implementation ##########

-------------------------------
! Found key : 8e73b0f7 da0e6452 c810f32b 809079e5 62f8ead2 522c6b7b
-------------------------------
Time elapsed: 4.930000 sec
-------------------------------

########## AES-192 Counter Mode Implementation ##########

-------------------------------
Plaintext : 6bc1bee2 2e409f96 e93d7e19 7393172a
Ciphertext : 6a1e395b 972c8729 e1bda841 5c25a12f
-------------------------------
Time elapsed: 3.450000 sec
-------------------------------

########## AES-256 Exhaustive Search Implementation ##########

-------------------------------
! Found key : 603deb10 15ca71be 2b73aef0 857d7781 1f352c07 3b6108d7 2d9810a3 0914dff4
-------------------------------
Time elapsed: 6.230000 sec
-------------------------------

########## AES-256 Counter Mode Implementation ##########

-------------------------------
Plaintext : 6bc1bee2 2e409f96 e93d7e19 7393172a
Ciphertext : c7d1375b ecae31e4 036c4e6b fb0aa4a0
-------------------------------
Time elapsed: 4.110000 sec


I want to know Time elapsed:2.820000sec about AES-128, what is this plaintext size?(throughoutput)？ Thanks

**Comment by cihangirtezcan** [comment]
Exhaustive search results tell you how many seconds it takes for you to try 2^35 keys.

Counter Mode results are the time it takes to encrypt a file of 2^35 blocks which equals to 512 GBs. So when you use AES with 128-bit key, it takes 2.82 seconds for you to encrypt 512 GBs. This equals to 181.56 GBs per second or 1.42 Terabits per second.

**Comment by cihangirtezcan** [comment]
Apparently you are using a powerful GPU like RTX 3080. Can you tell us your GPU model? It can be useful to other people for comparison.

**Comment by ccfeiker** [comment]
I use the NVIDIA Corporation TU102 [TITAN RTX]. the performance is good. I don’t know much about security. I want to choose an interface that can encrypt and decrypt with high throughput. I don’t know if there is any.

**Comment by cihangirtezcan** [comment]
Thanks a lot for the info.

Actually the file-encryption.cuh file has a function called "mainFileEncryption()" which allows you to encrypt any file (in counter mode encryption and decryption works in an identical way so you can also decrypt anything). And in there you can see that the test file we used was
const std::string filePath = "C://file-encryption-test//movie4.mp4";

So if you can compile file-encrption.cuh file and ask the file name/path from the user, you can encrypt any file you want. Of course, you need to choose your encryption key yourself. If you use the ones we put in the source code (stored in rk128[4] array), anybody can use them to decrypt your files.

When I have the time, I will try to compile these files on a Linux and make necessary corrections so that you can compile it without any errors.

**Comment by ccfeiker** [comment]
Thanks for your alot answer.
I try to modify file-encrption.cuh(c++ to c language, because nvcc is gcc complier), but show a Segmentation Fault, Maybe I Ignore somewhere.I waiting for your time to exchange this program.if possible can provide the encryption and the decryption API.Thank you so much.

**Comment by 905799575** [comment]
Do you have facebook or wechar? I can ask you more conveniently, or provide you with some help

**Comment by ccfeiker** [comment]
Do you have facebook or wechat? I can ask you more conveniently, or provide you with some help

**Comment by cihangirtezcan** [comment]
You can contact me via email or Linkedin. I have a unique name, so it is easy to find me :)

**Comment by ccfeiker** [comment]
OK...Perhaps cudaMalloc()->cudaHostAlloc() the performance may be better?

**Comment by cihangirtezcan** [comment]
It shouldn't provide any visible difference.

**Comment by ccfeiker** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
